login/config/routes.rb
Rails.application.routes.draw do
  

  resources :user
  resources :likes
  resources :secrets

  resources :sessions

end

login/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :secret
end

login/app/models/secret.rb
class Secret < ActiveRecord::Base
  belongs_to :user
  has_many :likes, dependent: :destroy
  # has_many :users, through: :likes
end

login/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :secrets
  has_many :likes, dependent: :destroy
  has_many :secrets, through: :likes
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
	validates :name, presence: true, length: { in: 2..20 }
	validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
	# validates :age, presence: true, numericality: { greater_than: 10, less_than: 150}
	
	before_save do 
		self.email.downcase!
		# self.first_name.capitalize!
	end	
end

login/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

login/app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :set_like, only: [:destroy]

def create
	
	@like = Like.new(:user_id => session[:user_id], :secret_id => params[:format])

      if @like.save
         redirect_to "/secrets"
      else
  		flash[:errors] = user.errors.full_messages
  		redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
  	  end
	
end


def destroy
    
    @like.destroy
    redirect_to "/secrets"
end


private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:secret_id, :user_id)
    end
  
end

login/app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
   before_action :set_secret, only: [:update, :destroy]

  def index
  	@secrets = Secret.all
  	@like = Like.new
  	@user = User.find(session[:user_id])
  end

  def destroy
    @secret.destroy
    redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
    
  end

  def create
  	@secret = Secret.new(secret_params)

      if @secret.save
         redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
      else
  		flash[:errors] = user.errors.full_messages
  		redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
  	  end
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_secret
      @secret = Secret.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def secret_params
      params.require(:secret).permit(:content, :user_id)
    end
  
end

login/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
  	# session[:user_id] = nil
    reset_session
  	redirect_to '/sessions/new'
  end



  def create
  	user = User.find_by(email: login_params[:email])

  	if user && user.authenticate(login_params[:password])
  		session[:user_id]=user.id
  		redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
      # redirect_to "/user/session[:user_id]", id: session[:user_id]
  	else
  		flash[:errors] = "Invalid email or Password"
  		redirect_to '/sessions/new'
  	end
  	
  end

  private
	  def login_params
	  	params.require(:user).permit(:email, :password)
	  end
end

login/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def show
    if params[:id] == session[:user_id].to_s
      @user = User.find_by(id: params[:id])
      @secret = Secret.new
      @secrets = Secret.where(user_id: params[:id])
      # @allsecrets = Secret.all
      # @allsecrets = Secret.where(likes: params[:id])

    else
      redirect_to :controller => 'user', :action => 'show', :id => session[:user_id]
    end
      
  end

  def create
  	user = User.new(user_params)

  	if user.save
  		session[:user_id]=user.id
  		redirect_to "/secrets"
  	else
  		flash[:errors] = user.errors.full_messages
  		redirect_to "/user/new"
  	end
  	
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

login/app/helpers/application_helper.rb
module ApplicationHelper
end

login/app/helpers/likes_helper.rb
module LikesHelper
end

login/app/helpers/secrets_helper.rb
module SecretsHelper
end

login/app/helpers/sessions_helper.rb
module SessionsHelper
end

login/app/helpers/user_helper.rb
module UserHelper
end

login/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Login1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

login/app/views/secrets/index.html.erb
<h1>Secrets</h1>

<p><%= session[:user_id] %> is logged in</p>

<% @secrets.each do |secret| %>
	<p> <%= secret.content %> 

		<% if secret.user_id == session[:user_id] %> 
			<button><%= link_to 'Delete', secret, method: :delete, data: { confirm: 'Are you sure?' } %></button>	
		<%end %>
		
		<p>  Likes:<%= secret.likes.count(:all) %>!

			<% unless @user.secrets.include?(secret) %>
				
				<%= link_to "Like", likes_path(secret), method: :post %>	

			<% else %>
				<% like = secret.likes.where(:user_id => @user.id).first %>
				<%= link_to 'Unlike', like_path(like), method: :delete %>
			<%end %>
		</p>
			

		
<hr>
	</p>
<%end %>


<a href="/sessions/<%= session[:user_id] %>" data-method="delete">Log Out</a>

<%= link_to "My Page", user_path(session[:user_id]) %>

login/app/views/user/new.html.erb
<h1>Register</h1>

<form action="/user" method="post">
	<label>
		Email: <input type="text" name="user[email]">
	</label><br>
	<label>
		Name: <input type="text" name="user[name]">
	</label><br>
	<label>
		Password: <input type="password" name="user[password]">
	</label><br>
	<label>
		Password Confirmation: <input type="password" name="user[password_confirmation]">
	</label><br>
	<input type="submit" name="Register" value="Log In">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
</form>

<% if flash[:errors] %>
	
	<% flash[:errors].each do |error| %>
	<p><%= error %></p>	
	<% end %>
<% end %>

login/app/views/user/show.html.erb
<h1><%= @user.name %></h1>

<%= form_for @secret do |f| %>
  <%= f.label :secret %>:
  <%= f.text_area :content %><br />

  <%= f.hidden_field :user_id, value: @user.id %> <br>
  

  <%= f.submit %>
<% end %>
<hr>

<h2>My Secrets</h2>
<% @secrets.each do |secret| %>
	<p> <%= secret.content %> 

		<%= link_to 'Delete', secret, method: :delete, data: { confirm: 'Are you sure?' } %>
		<p>  Likes:<%= secret.likes.count(:all) %>!</p>
			
	</p>
<%end %>

<hr>
<!-- 
<h2>My Secrets</h2>
<% @user.secrets.each do |secret| %>
	<p> <%= secret.content %> 

		<%= link_to 'Delete', secret, method: :delete, data: { confirm: 'Are you sure?' } %>
		<p>  Likes:<%= secret.likes.count(:all) %>!</p>
			
	</p>
<%end %>

<hr> -->

<h2>Secrets Liked:</h2>
	<% @user.likes.each do |like| %>
		
			<p> <%= like.secret.content %> 
			<p>  Likes:<%= like.secret.likes.count(:all) %>!</p>

			</p>
	<%end %>
<a href="/sessions/<%= session[:user_id] %>" data-method="delete">Log Out</a>
<!--  <%= link_to 'Back', :back %> -->

<%= link_to 'Main Page', secrets_path %>